trigger:
- master

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
  DOCKER_REGISTRY: 'cnab'

steps:
- task: Docker@1
  displayName: Login
  inputs:
    containerRegistryType: Container Registry
    dockerRegistryEndpoint: cnab-registry
    command: login

- task: HelmInstaller@0
  inputs:
    helmVersion: '2.12.1'
    checkLatestHelmVersion: false

- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace'

# TODO: Alternatively, we could run all duffle cmds via deislabs/duffle:latest docker container and remove this (and GO setup)
# Get Duffle
- script: |
    git clone https://github.com/deislabs/duffle.git '$(GOPATH)/src/github.com/deislabs/duffle'
    cd $(GOPATH)/src/github.com/deislabs/duffle
    make bootstrap build
    cp bin/duffle $(GOPATH)/bin/
  displayName: 'Install duffle'

# Fetch AKS Kubeconfig
- task: DownloadSecureFile@1
  inputs:
    secureFile: kubeconfig

- script: |
    export KUBECONFIG=$DOWNLOADSECUREFILE_SECUREFILEPATH
    export BUNDLE=example-voting-app
  displayName: 'Export KUBECONFIG and BUNDLE'

- script: |
    make build
  workingDirectory: '$(modulePath)'
  displayName: 'Build and sign bundle'

- script: |
    make push
  workingDirectory: '$(modulePath)'
  displayName: 'Push bundle invocation image(s)'

- script: |
    make install
  workingDirectory: '$(modulePath)'
  displayName: 'Install bundle'

- script: |
    make status
  workingDirectory: '$(modulePath)'
  displayName: 'Check bundle status'

- script: |
    make upgrade
  workingDirectory: '$(modulePath)'
  displayName: 'Upgrade bundle'

- script: |
    make status
  workingDirectory: '$(modulePath)'
  displayName: 'Check bundle status'

- script: |
    make uninstall
  workingDirectory: '$(modulePath)'
  displayName: 'Uninstall bundle'

